kind: Deployment
apiVersion: apps/v1
metadata:
  name: security-base-deploy
  namespace: security-base
  labels:
    app: security-base-deploy
  annotations:
    deployment.kubernetes.io/revision: '3'
    kubesphere.io/alias-name: security-base-deploy
    kubesphere.io/creator: admin
    kubesphere.io/description: 資安規則測試小系統
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-base-deploy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: security-base-deploy
    spec:
      containers:
        - name: security-base1
          image: 'sungpingdocker/security-base:v1'
          ports:
            - name: http-8030
              containerPort: 8030
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: security-base-svc
  namespace: security-base
  labels:
    app: security-base-svc
  annotations:
    kubesphere.io/alias-name: security-base-svc
    kubesphere.io/creator: admin
    kubesphere.io/description: |-
      資安規則測試小系統
      對外服務
spec:
  ports:
    - name: http-8030
      protocol: TCP
      port: 8030
      targetPort: 8030
  selector:
    app: security-base-deploy
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Local
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
